### ISSUE TITLE
Registration password

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/street-medicine-kc#17]
This one is from Roman:
I could not get far this time in registration process. I enter all required fields but get an error that my password is in incorrect format. However I used password “MyPassword123” and checked that a few times, so the password should satisfy the requirements and alert box should not show for that reason.

**Comment by jedgarbennett** [comment]
Damn it!  This has been an reoccurring issue.

**Comment by techgaun** [comment]
Can not replicate this issue. The regex in use works fine as per the requirement.
