### ISSUE TITLE
Readme.md: Describe homless demographics

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/street-medicine-kc#6]
Demographics
Needs
Abilities
Technology literacy/access

**Comment by jedgarbennett** [comment]
According to the NCHWIH report:
51.3% are single males.
24.7% are single females.
23% are families with children—the fastest growing segment.
5% are minors unaccompanied by adults.
1.37 million (or 39%) of the total homeless population are children under the age of 18.

**Comment by jedgarbennett** [comment]
![homeless data](https://cloud.githubusercontent.com/assets/17709785/18036030/69b0e5b0-6d27-11e6-9ba9-92ff567c9d9b.jpg)

**Comment by jedgarbennett** [comment]
[Homeless KC Fact Sheet .pdf](https://github.com/codeforkansascity/street-medicine-kc/files/441293/Homeless.KC.Fact.Sheet.pdf)

**Comment by tangospring** [comment]
Added demographics to repo Readme.md
